[package]
name = "aptos_sql"
version = "1.0.0"
authors = []

[addresses]
aptos_sql = "0x2"


[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
